services:
  - type: web
    name: majorproject
    env: node
    rootDir: majorproject
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 22.14.0
      - key: PORT
        value: 10000
